#log# Automatic Logger file. *** THIS MUST BE THE FIRST LINE ***
#log# DO NOT CHANGE THIS LINE OR THE TWO BELOW
#log# opts = Struct({'__allownew': True, 'logfile': 'campos_log.py', 'pylab': 1})
#log# args = []
#log# It is safe to make manual edits below here.
#log#-----------------------------------------------------------------------
_ip.magic("logstart campos_log.py")

_ip.magic("run campos")
_ip.magic("run -i campos")
show)(
show()
_ip.magic("run -i campos")
clf()
_ip.magic("run -i campos")
show()
_ip.magic("run campos")
clf()
_ip.magic("run campos")
show()
clf()
_ip.magic("run campos")
show()
_ip.magic("run campos")
clf()
clf()
_ip.magic("run campos")
show()
clf()
_ip.magic("run campos")
show()
_ip.magic("run campos")
show()
clf()
_ip.magic("run campos")
show()
_ip.magic("run campos")
clf()
show()
clf()
_ip.magic("run campos")
show()
clf()
figure(figsize(8,8))
figure(figsize=(8,8))
clf()
_ip.magic("run campos")
show()
clf()
_ip.magic("run campos")
show()
clf()
_ip.magic("run campos")
show()
#?quiver
clf)(
clf()
_ip.magic("run campos")
show()
#?quiver
